name: Deploy to wattbrews.me with tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Check if tag exists
        run: |
          git fetch --all --tags
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi

      - name: Prepare configuration file
        run: |
          sed -i 's|${LOG_ENV}|'"$LOG_ENV"'|g' mittere-config.yml
          sed -i 's|${LISTEN_PORT}|'"$LISTEN_PORT"'|g' mittere-config.yml
          sed -i 's|${MONGO_HOST}|'"$MONGO_HOST"'|g' mittere-config.yml
          sed -i 's|${MONGO_PORT}|'"$MONGO_PORT"'|g' mittere-config.yml
          sed -i 's|${MONGO_USER}|'"$MONGO_USER"'|g' mittere-config.yml
          sed -i 's|${MONGO_PASSWORD}|'"$MONGO_PASSWORD"'|g' mittere-config.yml
          sed -i 's|${MONGO_DATABASE}|'"$MONGO_DATABASE"'|g' mittere-config.yml
        env:
          LOG_ENV: ${{ vars.ENV }}
          LISTEN_PORT: ${{ vars.LISTEN_PORT }}
          MONGO_HOST: ${{ vars.MONGO_HOST }}
          MONGO_PORT: ${{ vars.MONGO_PORT }}
          MONGO_USER: ${{ vars.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_DATABASE: ${{ vars.MONGO_DATABASE }}


      - name: Copy Configuration to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "mittere-config.yml"
          target: "/etc/conf"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go application
        run: |
          go build -v -o mittere ./cmd/mittere

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "mittere"
          target: "/usr/local/bin/"

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            systemctl restart mittere.service