name: Deploy to dev server

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare configuration file
        run: |
          sed -i 's|${ENV}|'"ENV"'|g' mittere-config.yml
          sed -i 's|${LISTEN_PORT}|'"LISTEN_PORT"'|g' mittere-config.yml
          sed -i 's|${MONGO_HOST}|'"$MONGO_HOST"'|g' mittere-config.yml
          sed -i 's|${MONGO_PORT}|'"$MONGO_PORT"'|g' mittere-config.yml
          sed -i 's|${MONGO_USER}|'"$MONGO_USER"'|g' mittere-config.yml
          sed -i 's|${MONGO_PASSWORD}|'"$MONGO_PASSWORD"'|g' mittere-config.yml
          sed -i 's|${MONGO_DATABASE}|'"$MONGO_DATABASE"'|g' mittere-config.yml
        env:
          ENV: dev
          KEY_FILE: ${{ vars.LISTEN_PORT }}
          MONGO_HOST: ${{ vars.MONGO_HOST }}
          MONGO_PORT: ${{ vars.MONGO_PORT }}
          MONGO_USER: ${{ vars.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_DATABASE: ${{ vars.MONGO_DATABASE }}

      - name: Copy Configuration to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          source: "mittere-config.yml"
          target: "/etc/conf"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go application
        run: |
          go build -v -o mittere ./cmd/mittere

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          port: 22
          source: "mittere"
          target: "/usr/local/bin/"

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            systemctl restart mittere.service 
